"""The seed must be reproducible, and its numbers must be defensible.

Two distinct properties are asserted here:

  * **Determinism.** A fixed RNG seed produces byte-identical output, so a demo
    shown today and re-seeded next week is the same demo, and any bug found in a
    seeded row can be reproduced.
  * **Reproducibility of the z-scores.** Measurements are generated by inverting
    the WHO tables, so running `assess()` on a seeded height and weight must
    return the z-score the seed intended. This is what separates "realistic
    sample data" from "numbers someone typed in that happen to look plausible"
    -- and it is the difference between a demo a reviewer can audit and one they
    have to trust.
"""

from __future__ import annotations

import random
from datetime import date

import pytest

from app.growth.assess import STANDARD_2006, STANDARD_2007
from app.growth.lms import MAX_DAYS_2006
from app.seed import generate, photos, reference

TODAY = date(2026, 8, 28)
SEED = 20260828


def _children(seed: int = SEED):
    return generate.make_children(random.Random(seed), TODAY)


# --------------------------------------------------------------------------
# Determinism
# --------------------------------------------------------------------------


def test_same_seed_produces_identical_children() -> None:
    a, b = _children(), _children()
    assert [(c.name, c.dob, c.gender, c.target_haz) for c in a] == [
        (c.name, c.dob, c.gender, c.target_haz) for c in b
    ]


def test_a_different_seed_produces_different_children() -> None:
    assert [c.name for c in _children()] != [c.name for c in _children(999)]


def test_placeholder_images_are_byte_identical_across_runs() -> None:
    assert photos.variants(4) == photos.variants(4)


def test_compliance_generation_is_deterministic() -> None:
    awc = reference.AWCS[0]
    day = date(2026, 8, 24)
    a = generate.compliance_for_day(awc, day, random.Random(7))
    b = generate.compliance_for_day(awc, day, random.Random(7))
    assert a == b


# --------------------------------------------------------------------------
# The generated population matches the seed's stated intent
# --------------------------------------------------------------------------


def test_child_count_matches_the_reference_configuration() -> None:
    assert len(_children()) == sum(a["child_count"] for a in reference.AWCS)


def test_the_ashram_school_exercises_the_who_2007_reference() -> None:
    """Without a school-age cohort, deviation D1's code path would never run in
    a demo -- and the bug it exists to prevent would be invisible."""
    standards = set()
    rng = random.Random(SEED)
    for child in _children():
        if child.awc_code != "RJ-BSW-ANP-002":
            continue
        m = generate.measurement_for(child, TODAY, rng, 6)
        assert m is not None
        a = generate.assess_measurement(child, TODAY, *m)
        assert a is not None
        standards.add(a.standard_used)
    assert standards == {STANDARD_2007}


def test_anganwadi_children_straddle_both_references_at_61_months() -> None:
    """The Anganwadi cohort is NOT wholly a WHO 2006 population.

    ICDS covers 0-6 years, but the WHO Child Growth Standards stop at 61 months.
    A five-and-a-half-year-old at an Anganwadi centre therefore needs the WHO
    2007 reference exactly as an Ashram school child does.

    This is worth stating plainly because it widens the case for deviation D1.
    D1 was justified by the Ashram schools in Section 1, but even a pilot that
    only ever ran in Anganwadi centres would need it: roughly the oldest sixth
    of that cohort falls outside the 0-60m tables. Applying weight-for-height to
    them would produce clinically invalid numbers for children the system is
    specifically meant to be watching.

    The split must land exactly on the table boundary, never anywhere else.
    """
    rng = random.Random(SEED)
    seen: dict[str, list[int]] = {STANDARD_2006: [], STANDARD_2007: []}
    for child in _children():
        if child.awc_code == "RJ-BSW-ANP-002":
            continue
        m = generate.measurement_for(child, TODAY, rng, 6)
        a = generate.assess_measurement(child, TODAY, *m)
        seen[a.standard_used].append(a.age_days)

    assert seen[STANDARD_2006], "no under-fives in the Anganwadi cohort"
    assert seen[STANDARD_2007], (
        "no over-61-month children: the Anganwadi seed no longer covers the "
        "full 0-6y ICDS age range, so deviation D1 goes untested here"
    )
    assert max(seen[STANDARD_2006]) <= MAX_DAYS_2006
    assert min(seen[STANDARD_2007]) > MAX_DAYS_2006


# --------------------------------------------------------------------------
# The audit property
# --------------------------------------------------------------------------


def test_generated_measurements_score_back_to_their_target_zscores() -> None:
    """Invert a target z-score to a measurement, score the measurement, get the
    target back. Small tolerance because heights and weights are rounded to the
    0.1 a field scale actually reports -- that rounding is the only error."""
    rng = random.Random(SEED)
    checked = 0
    for child in _children():
        m = generate.measurement_for(child, TODAY, rng, visit=1)
        if m is None:
            continue
        a = generate.assess_measurement(child, TODAY, *m)
        if a is None or a.haz is None:
            continue
        # visit=1 means drift is near zero, so haz should sit within noise of
        # the child's target.
        assert a.haz == pytest.approx(child.target_haz, abs=0.35)
        checked += 1
    assert checked > 100


def test_every_generated_measurement_is_scoreable() -> None:
    """A seeded row that assess() cannot score would be a row no reviewer can
    verify. There must be none."""
    rng = random.Random(SEED)
    for child in _children():
        for visit, when in enumerate(generate.growth_visits(TODAY), start=1):
            m = generate.measurement_for(child, when, rng, visit)
            assert m is not None, f"could not generate for {child.name} at {when}"
            assert generate.assess_measurement(child, when, *m) is not None


def test_prevalence_is_in_a_plausible_range_for_the_tribal_belt() -> None:
    """Not an exact assertion -- the seed reports its achieved numbers rather
    than promising them. This is a guard against the distribution drifting into
    something indefensible, such as no malnutrition at all or nothing but."""
    rng = random.Random(SEED)
    stunted = wasted = total = 0
    for child in _children():
        m = generate.measurement_for(child, TODAY, rng, 6)
        a = generate.assess_measurement(child, TODAY, *m)
        if a is None:
            continue
        total += 1
        if a.classification_detail["stunting"] in {"stunted", "severely_stunted"}:
            stunted += 1
        acute = {
            "moderate_acute_malnutrition",
            "severe_acute_malnutrition",
            "thinness",
            "severe_thinness",
        }
        if (
            a.classification_detail["wasting"] in acute
            or a.classification_detail["thinness"] in acute
        ):
            wasted += 1
    assert 0.20 <= stunted / total <= 0.55, f"stunting {stunted / total:.1%} is implausible"
    assert 0.05 <= wasted / total <= 0.35, f"wasting {wasted / total:.1%} is implausible"


# --------------------------------------------------------------------------
# Menu compliance invariants
# --------------------------------------------------------------------------


def test_flagged_days_always_carry_a_reason() -> None:
    """The schema enforces this too. A flagged day with no reason is useless to
    the officer who has to act on it."""
    rng = random.Random(SEED)
    rows = [
        generate.compliance_for_day(reference.AWCS[0], d, rng) for d in generate.serving_days(TODAY)
    ]
    assert any(r["flagged"] for r in rows), "an all-green seed demonstrates nothing"
    for r in rows:
        assert (r["flag_reason"] is not None) == r["flagged"]
        if r["flagged"]:
            # Bilingual, like every other user-facing string.
            assert " | " in r["flag_reason"]


def test_compliance_percentage_is_consistent_with_the_item_lists() -> None:
    rng = random.Random(SEED)
    for day in generate.serving_days(TODAY):
        r = generate.compliance_for_day(reference.AWCS[0], day, rng)
        expected = round(100.0 * len(r["detected_items"]) / len(r["prescribed_items"]), 2)
        assert r["compliance_pct"] == expected
        assert 0 <= r["compliance_pct"] <= 100
        assert set(r["detected_items"]) <= set(r["prescribed_items"])


def test_sunday_is_never_a_serving_day() -> None:
    assert all(d.weekday() != 6 for d in generate.serving_days(TODAY))


def test_menu_cycle_covers_every_serving_weekday() -> None:
    assert set(reference.MENU_CYCLE) == {0, 1, 2, 3, 4, 5}
    known = {m["code"] for m in reference.MENU_ITEMS}
    for items in reference.MENU_CYCLE.values():
        assert set(items) <= known, "menu cycle references an unknown item code"


# --------------------------------------------------------------------------
# Section 12: nothing here describes a real person
# --------------------------------------------------------------------------


def test_test_phone_numbers_are_in_the_reserved_range() -> None:
    for worker in reference.FIELD_WORKERS:
        assert worker["phone"].startswith("99999"), "seed must not contain a real number"


def test_reference_data_is_bilingual_everywhere_it_is_displayed() -> None:
    for awc in reference.AWCS:
        assert awc["name_hi"] and awc["district_hi"] and awc["block_hi"]
    for item in reference.MENU_ITEMS:
        assert item["name_hi"] and item["name_en"]
